/**
 * Google Docs API Integration Service
 * Generates formatted study guides, syllabus documents, and revision sheets directly into Google Docs.
 */

import { getOrRequestWorkspaceToken } from './googleAuthService';
import { Subject, FlashcardDeck, StudyPlan, RevisionItem } from '../types';

export interface GoogleDocResult {
  documentId: string;
  title: string;
  documentUrl: string;
}

/**
 * Creates a blank Google Doc and inserts structured text into it.
 */
export async function createGoogleDocWithContent(title: string, rawTextContent: string): Promise<GoogleDocResult> {
  const token = await getOrRequestWorkspaceToken();

  // 1. Create the document
  const createResponse = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      title: title
    })
  });

  if (!createResponse.ok) {
    const err = await createResponse.json().catch(() => ({}));
    throw new Error(err.error?.message || `Failed to create Google Doc (${createResponse.status})`);
  }

  const docData = await createResponse.json();
  const documentId = docData.documentId;

  // 2. Insert the formatted text content
  if (rawTextContent && rawTextContent.trim().length > 0) {
    const updateResponse = await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        requests: [
          {
            insertText: {
              location: {
                index: 1
              },
              text: rawTextContent
            }
          }
        ]
      })
    });

    if (!updateResponse.ok) {
      console.warn('Batch update note for Google Doc:', await updateResponse.text());
    }
  }

  return {
    documentId,
    title,
    documentUrl: `https://docs.google.com/document/d/${documentId}/edit`
  };
}

/**
 * Exports a Subject's syllabus into a Google Doc.
 */
export async function exportSyllabusToGoogleDoc(subject: Subject): Promise<GoogleDocResult> {
  const totalTopics = subject.chapters.reduce((sum, ch) => sum + ch.topics.length, 0);
  const completedTopics = subject.chapters.reduce(
    (sum, ch) => sum + ch.topics.filter(t => t.status === 'Completed' || t.status === 'Mastered').length,
    0
  );
  const progressPct = totalTopics > 0 ? Math.round((completedTopics / totalTopics) * 100) : 0;

  let docContent = `${subject.icon || '📖'} ${subject.name.toUpperCase()} - ACADEMIC SYLLABUS & MASTERY TRACKER\n`;
  docContent += `Description: ${subject.description || 'Curriculum Syllabus'} | Total Topics: ${totalTopics} | Completed: ${completedTopics} (${progressPct}%)\n`;
  docContent += `Generated by StudyOS on ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}\n\n`;
  docContent += `========================================================\n\n`;

  subject.chapters.forEach((chap, cIdx) => {
    docContent += `CHAPTER ${cIdx + 1}: ${chap.name.toUpperCase()} (${chap.topics.length} topics)\n`;
    docContent += `--------------------------------------------------------\n`;

    chap.topics.forEach((topic, tIdx) => {
      const check = topic.status === 'Completed' || topic.status === 'Mastered' ? '[X]' : '[ ]';
      const estMin = topic.estimatedMinutes ? ` (~${topic.estimatedMinutes}m)` : '';
      docContent += `  ${cIdx + 1}.${tIdx + 1} ${check} ${topic.name} [Status: ${topic.status}]${estMin}\n`;
      if (topic.subtopics && topic.subtopics.length > 0) {
        topic.subtopics.forEach((st) => {
          const stCheck = st.completed ? '[✓]' : '[ ]';
          docContent += `      ${stCheck} ${st.name}\n`;
        });
      }
    });
    docContent += `\n`;
  });

  docContent += `========================================================\n`;
  docContent += `STUDY NOTES & ACTION PLAN:\n`;
  docContent += `- 1. Active Recall: Review definitions and self-test after completing each topic.\n`;
  docContent += `- 2. Spaced Repetition: Re-visit tough topics at Day 1, Day 3, and Day 7.\n`;
  docContent += `- 3. Track progress and log sessions at your StudyOS workspace.\n`;

  return await createGoogleDocWithContent(`Syllabus - ${subject.name} (StudyOS)`, docContent);
}

/**
 * Exports an Active-Recall Flashcard Deck to a Google Doc.
 */
export async function exportFlashcardDeckToGoogleDoc(deck: FlashcardDeck): Promise<GoogleDocResult> {
  const masteredCount = deck.cards.filter(c => c.mastered).length;
  let docContent = `⚡ ACTIVE RECALL STUDY DECK: ${deck.title.toUpperCase()}\n`;
  docContent += `Subject: ${deck.subjectName} | Total Cards: ${deck.cards.length} | Mastered: ${masteredCount}\n`;
  if (deck.description) {
    docContent += `Description: ${deck.description}\n`;
  }
  docContent += `Generated by StudyOS on ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}\n\n`;
  docContent += `========================================================\n\n`;

  deck.cards.forEach((card, idx) => {
    const status = card.mastered ? 'MASTERED' : `Interval: ${card.intervalDays || 1}d`;
    docContent += `CARD #${idx + 1} [Status: ${status}]\n`;
    docContent += `PROMPT / QUESTION:\n${card.front}\n\n`;
    docContent += `ANSWER / KEY CONCEPT:\n${card.back}\n\n`;
    if (card.mnemonic) {
      docContent += `💡 MNEMONIC / MEMORY HOOK: ${card.mnemonic}\n\n`;
    }
    docContent += `--------------------------------------------------------\n\n`;
  });

  return await createGoogleDocWithContent(`Flashcards - ${deck.title} (StudyOS)`, docContent);
}

/**
 * Exports a Study Plan schedule to a Google Doc.
 */
export async function exportStudyPlanToGoogleDoc(plan: StudyPlan): Promise<GoogleDocResult> {
  const totalMinutes = plan.topics.reduce((acc, t) => acc + (t.estimatedMinutes || 60), 0);
  const completedCount = plan.topics.filter(t => t.completed).length;

  let docContent = `📅 STUDY PLAN: ${plan.title.toUpperCase()}\n`;
  docContent += `Date: ${plan.date} | Total Estimated Time: ${Math.round(totalMinutes / 60 * 10) / 10}h | Completed: ${completedCount}/${plan.topics.length}\n`;
  if (plan.reasoning) {
    docContent += `Strategy: ${plan.reasoning}\n`;
  }
  docContent += `Generated by StudyOS on ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}\n\n`;
  docContent += `========================================================\n\n`;

  if (plan.topics && plan.topics.length > 0) {
    docContent += `TASKS & TOPICS:\n`;
    plan.topics.forEach((t, idx) => {
      const check = t.completed ? '[✓]' : '[ ]';
      const prio = t.priority ? `[${t.priority} Priority]` : '';
      const time = t.estimatedMinutes ? `${t.estimatedMinutes}m` : '60m';
      docContent += `${idx + 1}. ${check} ${t.subjectName} > ${t.chapterName} > ${t.topicName} ${prio} (${time})\n`;
      if (t.reason) {
        docContent += `    Reason: ${t.reason}\n`;
      }
      if (t.completionDetails) {
        docContent += `    Notes: ${t.completionDetails}\n`;
      }
    });
    docContent += `\n`;
  }

  return await createGoogleDocWithContent(`Study Plan - ${plan.title} (StudyOS)`, docContent);
}
